{% set name = "locklib" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/locklib-{{ version }}.tar.gz
  sha256: c988287dca643017f6838a0101a9055a54f5ee36f9be8e49d73d566804e6faee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - pip
  run:
    - python >=3.7

test:
  imports:
    - locklib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pomponchik/locklib
  summary: Useful additions to the standard thread synchronization tools.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
