{% set name = "locklib" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/locklib-{{ version }}.tar.gz
  sha256: 2d622db4c80984d81f186acb4db33e61978ab362f4535381b313282fcef6dc5f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==68.0.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - locklib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pomponchik/locklib
  summary: Useful additions to the standard thread synchronization tools.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
