schema_version: 1

context:
  name: locklib
  version: "0.0.20"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/locklib-${{ version }}.tar.gz
  sha256: 286dfc92df9e5b29ce72eac67188b32cd94dbd6acfa2f67762bcd866ed308a10

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools ==68.0.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - locklib
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Useful additions to the standard thread synchronization tools.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pomponchik/locklib

extra:
  recipe-maintainers:
    - thewchan
